version: "3.9"
networks:
  nodes_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.2.0/16
services:
  # Super nodes.
  super-node-arthur:
    container_name: super-node-arthur
    networks:
      nodes_network:
        ipv4_address: 172.24.2.1
    build: .
    entrypoint: npm run as-super-node -- "super-node-arthur"
  # Peer Nodes.
  peer-node-zeca:
    container_name: peer-node-zeca
    networks:
      nodes_network:
        ipv4_address: 172.24.2.4
    volumes:
      - type: bind
        source: ./src/configurations/requests/peer-node-zeca.json
        target: /home/trab-1-prog-distr/build/configurations/requests/peer-node-zeca.json
    build: .
    entrypoint: npm run as-peer-node -- "peer-node-zeca"
  peer-node-maria:
    container_name: peer-node-maria
    networks:
      nodes_network:
        ipv4_address: 172.24.2.5
    volumes:
      - type: bind
        source: ./src/configurations/requests/peer-node-maria.json
        target: /home/trab-1-prog-distr/build/configurations/requests/peer-node-maria.json
    build: .
    entrypoint: npm run as-peer-node -- "peer-node-maria"
  peer-node-carlos:
    container_name: peer-node-carlos
    networks:
      nodes_network:
        ipv4_address: 172.24.2.6
    volumes:
      - type: bind
        source: ./src/configurations/requests/peer-node-carlos.json
        target: /home/trab-1-prog-distr/build/configurations/requests/peer-node-carlos.json
    build: .
    entrypoint: npm run as-peer-node -- "peer-node-carlos"
