version: "3.9"
services:
  # Super nodes.
  super-node-1:
    container_name: super-node-1
    ports:
      - 8000:8000/udp
    build: .
    entrypoint: npm run as-super-node "super-node-1"
  # Peer Nodes.
  peer-node-1:
    container_name: peer-node-1
    ports:
      - 9000:9000/udp
    build: .
    volumes:
      - type: bind
        source: ./src/configurations/requests/peer-node-1.json
        target: /home/trab-1-prog-distr/build/configurations/requests/peer-node-1.json
    entrypoint: npm run as-peer-node "peer-node-1" "9000" "src/resources/books-1"
